name: Adhoc Build New Relic ZTS Agent

permissions:
  actions: write
  contents: read

env:
  upstream-repo: theophileds/newrelic-php-agent-zts
  upstream-ref: zts-support
  frankenphp-image: dunglas/frankenphp
  artifact-name: newrelic-php-agent-zts

on:
  workflow_dispatch:
    inputs:
      frankenphp-version:
        description: FrankenPHP tag for PHP_IMAGE build-arg (e.g. 1-php8.4)
        required: true
        default: 1-php8.5

jobs:
  adhoc:
    name: Adhoc build
    runs-on: ubuntu-latest
    steps:
      - name: Get agent artifact
        uses: ./.github/workflows/prepare.yaml

      - name: Build agent
        uses: ./.github/workflows/build.yaml
        with:
          frankenphp-version: ${{ inputs.frankenphp-version }}
  