name: Adhoc Build New Relic ZTS Agent

permissions:
  actions: write
  contents: read

env:
  upstream-repo: theophileds/newrelic-php-agent-zts
  upstream-ref: zts-support
  frankenphp-image: dunglas/frankenphp
  artifact-name: newrelic-php-agent-zts

on:
  workflow_dispatch:
    inputs:
      frankenphp-version:
        description: FrankenPHP tag for PHP_IMAGE build-arg (e.g. 1-php8.4)
        required: true
        default: 1-php8.5

jobs:
  prepare:
    name: Prepare agent sources
    uses: ./.github/workflows/prepare.yaml
    secrets: inherit

  build:
    name: Build and push image
    needs: prepare
    uses: ./.github/workflows/build.yaml
    with:
      frankenphp-version: ${{ inputs['frankenphp-version'] }}
    secrets: inherit
