name: Sync tags from dunglas/frankenphp

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yaml

  build:
    name: "Build ${{ matrix.frankenphp-version }}"
    needs: [ prepare ]
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        frankenphp-version: [ '1', '1.10', '1.11', '1.12' ]
        php-version: ['8.1', '8.2', '8.3', '8.4', '8.5']
        os: ['', 'trixie', 'bookworm']
    uses: ./.github/workflows/build.yaml
    with:
      frankenphp-version: ${{ matrix.frankenphp-version }}-php${{ matrix.php-version }}${{ matrix.os }}
